name: Update on push
on:
  push:
    branches:
      - main
jobs:
  update:
    name: update data
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      - name: install python and dependencies
        run: |
          pip install -r requirements.txt
      - name: import github secrets and run notebooks
        env: 
          GHD_TWITTER_ACCESSTOKEN: ${{ secrets.GHD_TWITTER_ACCESSTOKEN }}
          GHD_TWITTER_ACCESSTOKENSECRET: ${{ secrets.GHD_TWITTER_ACCESSTOKENSECRET }}
          GHD_TWITTER_APIKEY: ${{ secrets.GHD_TWITTER_APIKEY }}
          GHD_TWITTER_APIKEYSECRET: ${{ secrets.GHD_TWITTER_APIKEYSECRET }}
          GHD_TWITTER_BEARERTOKEN: ${{ secrets.GHD_TWITTER_BEARERTOKEN }}
          GHD_TWITTER_CLIENTID: ${{ secrets.GHD_TWITTER_CLIENTID }}
          GHD_TWITTER_CLIENTSECRET: ${{ secrets.GHD_TWITTER_CLIENTSECRET }}
        id: run_notebooks
        run: |
          jupyter nbconvert --to notebook --inplace --ExecutePreprocessor.kernel_name=python3 --execute MotherScript.ipynb
      - name: git status
        id: git-status
        run: |
          git config --global user.email "test-bot@example.com"
          git config --global user.name "test-bot"
          echo ::set-output name=result::$(git status ./ | tr -d "\n" | grep -c "nothing to commit")
      - name: commit
        if: steps.git-status.outputs.result == 0
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          DATE: ${{ steps.update-script.outputs.result }}
        run: |
          git add -A
          git commit -m "[ci] $(date +%H)"
          git push -q "https://$GH_TOKEN@github.com/dquintani/update.git" main
